# Site settings
title: 66 Sherwin Road
email: hello@66sherwinroad.co.uk
description: >-
  66 Sherwin Road is a stylish and popular 6-bed student house
  located in a quiet street in the heart of Lenton, Nottingham.
twitter_username: lentonrentals

# Build settings
markdown: kramdown
sass:
  load_paths:
    - _scss
    - node_modules
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules